**Practical 1** :
Study the Data Analytics lifecycle and perform data acquisition from CSV,
Excel, and JSON files using Pandas.

step 1 - import pandas

In [ ]:
# Import the Pandas library
import pandas as pd

Step - 2 Create sample dataset

In [ ]:
# Create a dictionary containing student data
data = {
    "ID":[101,102,103,104,105,106,107],
    "Name":["Rahul","Priya","Amit","Riya","Karan","Krisha","Harry"],
    "Age":[20,21,19,20,22,24,28],
    "City":["Surat","Navsari","Valsad","Bharuch","Surat","Gandhinagar","Ahemdabad"],
    "Marks":[85,92,78,88,81,84,90]
}

step-3 create a dataFrame

In [ ]:
# Create a DataFrame from the dictionary 'data'
df = pd.DataFrame(data)
# Display the DataFrame
df

    ID    Name  Age         City  Marks
0  101   Rahul   20        Surat     85
1  102   Priya   21      Navsari     92
2  103    Amit   19       Valsad     78
3  104    Riya   20      Bharuch     88
4  105   Karan   22        Surat     81
5  106  Krisha   24  Gandhinagar     84
6  107   Harry   28    Ahemdabad     90

step-4 save data as a csv file

In [ ]:
# Save the DataFrame to a CSV file without row indices
df.to_csv("student.csv", index=False)
# Display a success message
print("CSV file created successfully")

CSV file created successfully

step-5 save data as an excel file

In [ ]:
# Save the DataFrame to an Excel file without row indices
df.to_excel("student.xlsx", index=False)

# Display a success message
print("Excel file created successfully")

Excel file created successfully

step-6 save data as a JSON file

In [ ]:
# Save the DataFrame to a JSON file in records format with indentation
df.to_json("student.json", orient="records", indent=4)
# Display a success message
print("JSON file created successfully")

JSON file created successfully

step-7 Read the CSV file

In [ ]:
# Read data from the CSV file into a DataFrame
df_csv = pd.read_csv("student.csv")

# Display the DataFrame
df_csv

    ID    Name  Age         City  Marks
0  101   Rahul   20        Surat     85
1  102   Priya   21      Navsari     92
2  103    Amit   19       Valsad     78
3  104    Riya   20      Bharuch     88
4  105   Karan   22        Surat     81
5  106  Krisha   24  Gandhinagar     84
6  107   Harry   28    Ahemdabad     90

step-8 read the excel file

In [ ]:
# Read data from the Excel file into a DataFrame
df_excel = pd.read_excel("student.xlsx")

# Display the DataFrame
df_excel

    ID    Name  Age         City  Marks
0  101   Rahul   20        Surat     85
1  102   Priya   21      Navsari     92
2  103    Amit   19       Valsad     78
3  104    Riya   20      Bharuch     88
4  105   Karan   22        Surat     81
5  106  Krisha   24  Gandhinagar     84
6  107   Harry   28    Ahemdabad     90

step-9 read the json file

In [ ]:
# Read data from the JSON file into a DataFrame
df_csv = pd.read_json("student.json")
# Display the DataFrame
df_csv

    ID    Name  Age         City  Marks
0  101   Rahul   20        Surat     85
1  102   Priya   21      Navsari     92
2  103    Amit   19       Valsad     78
3  104    Riya   20      Bharuch     88
4  105   Karan   22        Surat     81
5  106  Krisha   24  Gandhinagar     84
6  107   Harry   28    Ahemdabad     90

step-10 display the first five records

In [ ]:
# Display the first 5 rows of the DataFrame
df_csv.head()

    ID   Name  Age     City  Marks
0  101  Rahul   20    Surat     85
1  102  Priya   21  Navsari     92
2  103   Amit   19   Valsad     78
3  104   Riya   20  Bharuch     88
4  105  Karan   22    Surat     81

step -11 display the last five records

In [ ]:
# Display the last 5 rows of the DataFrame
df_csv.tail()

    ID    Name  Age         City  Marks
2  103    Amit   19       Valsad     78
3  104    Riya   20      Bharuch     88
4  105   Karan   22        Surat     81
5  106  Krisha   24  Gandhinagar     84
6  107   Harry   28    Ahemdabad     90

STEP -12 display dataset information

In [ ]:
# Display information about the DataFrame (data types, non-null values, memory usage)
df_csv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ID      7 non-null      int64
 1   Name    7 non-null      object
 2   Age     7 non-null      int64
 3   City    7 non-null      object
 4   Marks   7 non-null      int64
dtypes: int64(3), object(2)
memory usage: 412.0+ bytes

step -13 display statistical summary

In [ ]:
# Generate statistical summary of numerical columns
df_csv.describe()

               ID        Age      Marks
count    7.000000   7.000000   7.000000
mean   104.000000  22.000000  85.428571
std      2.160247   3.109126   4.961759
min    101.000000  19.000000  78.000000
25%    102.500000  20.000000  82.500000
50%    104.000000  21.000000  85.000000
75%    105.500000  23.000000  89.000000
max    107.000000  28.000000  92.000000

step-14 display dataset shape

In [ ]:
# Display the number of rows and columns in the DataFrame
df_csv.shape

(7, 5)

step-15 display column names

In [ ]:
# Display the column names of the DataFrame
df_csv.columns

Index(['ID', 'Name', 'Age', 'City', 'Marks'], dtype='object')

step-16 display data type

In [ ]:
# Display the data type of each column
df_csv.dtypes

ID        int64
Name     object
Age       int64
City     object
Marks     int64
dtype: object

step-17 check for missing valsues

In [ ]:
# Count missing (null) values in each column
df_csv.isnull().sum()

ID       0
Name     0
Age      0
City     0
Marks    0
dtype: int64

step -18 display a single column

In [ ]:
# Display the single column
# Display the 'Marks' column
df_csv["Marks"]

0    85
1    92
2    78
3    88
4    81
5    84
6    90
Name: Marks, dtype: int64

step-19 display multiple columns

In [ ]:
# Display the Multiple column
# Display only the Name, Age, and Marks columns
df_csv[["Name","Age","Marks"]]

     Name  Age  Marks
0   Rahul   20     85
1   Priya   21     92
2    Amit   19     78
3    Riya   20     88
4   Karan   22     81
5  Krisha   24     84
6   Harry   28     90

step-20 filter records

In [ ]:
# Filter and display records where Marks are greater than 90
df_csv[df_csv["Marks"] > 90]

    ID   Name  Age     City  Marks
1  102  Priya   21  Navsari     92

step -21 calculate average marks

In [ ]:
# Calculate the average Marks
df_csv["Marks"].mean()

np.float64(85.42857142857143)

step-22 sort data

In [ ]:
# Sort the DataFrame by Marks in descending order
df_csv.sort_values(by="Marks", ascending=False)

    ID    Name  Age         City  Marks
1  102   Priya   21      Navsari     92
6  107   Harry   28    Ahemdabad     90
3  104    Riya   20      Bharuch     88
0  101   Rahul   20        Surat     85
5  106  Krisha   24  Gandhinagar     84
4  105   Karan   22        Surat     81
2  103    Amit   19       Valsad     78

step-23 display dataset

In [ ]:
# Display the entire DataFrame
df_csv

    ID    Name  Age         City  Marks
0  101   Rahul   20        Surat     85
1  102   Priya   21      Navsari     92
2  103    Amit   19       Valsad     78
3  104    Riya   20      Bharuch     88
4  105   Karan   22        Surat     81
5  106  Krisha   24  Gandhinagar     84
6  107   Harry   28    Ahemdabad     90