Practical 2: Perform Data Inspection, Cleaning , Handling missing values duplicate remove And Data Transformation Using Pandas

Step 1: Import Required Library

In [57]:
# Import the pandas library.
# Pandas is used for data manipulation and analysis.
# 'pd' is the standard alias used to access pandas functions.

import pandas as pd

Step 2: Create a sample dataset

In [58]:
# Create a sample student dataset
data = {
    "ID" : [101, 102, 103, 104, 104, 105, 106 ,107],
    "Name" : ["Rahul", "Priya", None ,"Amit", "Riya", "Ajay", "Naresh", "jenil"],
    "Age" : [20,21,None,20,20,22,23,28],
    "City" : ["Surat", "Navsari", "Surat", "Bharuch", "Bharuch", "Navsari", "Surat", "Ahmedabad"],
    "Marks" : [85,None,78,88,88,81,90,93]
 }

In [59]:
# Create a DataFrame from the dictionary
df = pd.DataFrame(data)

# Display the DataFrame
df

    ID    Name   Age       City  Marks
0  101   Rahul  20.0      Surat   85.0
1  102   Priya  21.0    Navsari    NaN
2  103    None   NaN      Surat   78.0
3  104    Amit  20.0    Bharuch   88.0
4  104    Riya  20.0    Bharuch   88.0
5  105    Ajay  22.0    Navsari   81.0
6  106  Naresh  23.0      Surat   90.0
7  107   jenil  28.0  Ahmedabad   93.0

Step 3: Inspect the Dataset

In [60]:
#Display the first 5 rows of the DataFrame
df.head()

    ID   Name   Age     City  Marks
0  101  Rahul  20.0    Surat   85.0
1  102  Priya  21.0  Navsari    NaN
2  103   None   NaN    Surat   78.0
3  104   Amit  20.0  Bharuch   88.0
4  104   Riya  20.0  Bharuch   88.0

In [61]:
## Display the last 5 rows of the DataFrame
df.tail()

    ID    Name   Age       City  Marks
3  104    Amit  20.0    Bharuch   88.0
4  104    Riya  20.0    Bharuch   88.0
5  105    Ajay  22.0    Navsari   81.0
6  106  Naresh  23.0      Surat   90.0
7  107   jenil  28.0  Ahmedabad   93.0

In [62]:
# Display information about the DataFrame
# Display the columns, data types, and missing values
# Check the DataFrame structure, data types, and non-null values

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ID      8 non-null      int64
 1   Name    7 non-null      object
 2   Age     7 non-null      float64
 3   City    8 non-null      object
 4   Marks   7 non-null      float64
dtypes: float64(2), int64(1), object(2)
memory usage: 452.0+ bytes

In [ ]:
# Generate statistical information for numerical columns
# Display count, mean, standard deviation, minimum, maximum, and quartiles
df.describe()

           ID        Age      Marks
count    8.00   7.000000   7.000000
mean   104.00  22.000000  86.142857
std      2.00   2.886751   5.209881
min    101.00  20.000000  78.000000
25%    102.75  20.000000  83.000000
50%    104.00  21.000000  88.000000
75%    105.25  22.500000  89.000000
max    107.00  28.000000  93.000000

In [ ]:
# Display the dimensions of dataset
df.shape

(8, 5)

In [ ]:
# display the data type of each column
df.dtypes

ID         int64
Name      object
Age      float64
City      object
Marks    float64
dtype: object

In [ ]:
#display the all the columns in dataframe
df.columns

Index(['ID', 'Name', 'Age', 'City', 'Marks'], dtype='object')

Step 4: check missing values

In [ ]:
# check for missing (null) values in every column
df.isnull()

      ID   Name    Age   City  Marks
0  False  False  False  False  False
1  False  False  False  False   True
2  False   True   True  False  False
3  False  False  False  False  False
4  False  False  False  False  False
5  False  False  False  False  False
6  False  False  False  False  False
7  False  False  False  False  False

In [63]:
# Display the total number of missing values in each column
df.isnull().sum()

ID       0
Name     1
Age      1
City     0
Marks    1
dtype: int64

In [65]:
# Count total missing values in the dataset
df.isnull().sum().sum()

np.int64(2)

step 5 : Fill missing values

In [64]:
# Calculate the average of the "Marks" column
# and replace missing values with that average

df["Marks"] = df["Marks"].fillna(df["Marks"].mean())

# Display the updated dataset
df

    ID    Name   Age       City      Marks
0  101   Rahul  20.0      Surat  85.000000
1  102   Priya  21.0    Navsari  86.142857
2  103    None   NaN      Surat  78.000000
3  104    Amit  20.0    Bharuch  88.000000
4  104    Riya  20.0    Bharuch  88.000000
5  105    Ajay  22.0    Navsari  81.000000
6  106  Naresh  23.0      Surat  90.000000
7  107   jenil  28.0  Ahmedabad  93.000000

Fill missing age

In [66]:
# Calculate the average of the "Age" column
# and replace missing values with that average
df["Age"] = df["Age"].fillna(df["Age"].mean())

# Display the updated dataset
df

    ID    Name   Age       City      Marks
0  101   Rahul  20.0      Surat  85.000000
1  102   Priya  21.0    Navsari  86.142857
2  103    None  22.0      Surat  78.000000
3  104    Amit  20.0    Bharuch  88.000000
4  104    Riya  20.0    Bharuch  88.000000
5  105    Ajay  22.0    Navsari  81.000000
6  106  Naresh  23.0      Surat  90.000000
7  107   jenil  28.0  Ahmedabad  93.000000

Fill missing Name

In [67]:
# Calculate the most common name in the "Name" column
# and replace missing values with that name
df["Name"] = df["Name"].fillna("Unknown")

# Display the updated dataset
df

    ID     Name   Age       City      Marks
0  101    Rahul  20.0      Surat  85.000000
1  102    Priya  21.0    Navsari  86.142857
2  103  Unknown  22.0      Surat  78.000000
3  104     Amit  20.0    Bharuch  88.000000
4  104     Riya  20.0    Bharuch  88.000000
5  105     Ajay  22.0    Navsari  81.000000
6  106   Naresh  23.0      Surat  90.000000
7  107    jenil  28.0  Ahmedabad  93.000000

Step 6: Detect duplicate records

In [ ]:
#check wheter duplicate records
df.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
dtype: bool

In [ ]:
#count the total number of duplicate rows
df.duplicated().sum()

np.int64(0)

step 7: remove duplicate records

In [72]:
# Remove duplicate rows from the dataset
df = df.drop_duplicates()

# Display the updated dataset
df

    ID     Name  Age       City      Score  Final Score
0  101    RAHUL   20      Surat  85.000000    90.000000
1  102    PRIYA   21    Navsari  86.142857    91.142857
2  103  UNKNOWN   22      Surat  78.000000    83.000000
3  104     AMIT   20    Bharuch  88.000000    93.000000
4  104     RIYA   20    Bharuch  88.000000    93.000000
5  105     AJAY   22    Navsari  81.000000    86.000000
6  106   NARESH   23      Surat  90.000000    95.000000
7  107    JENIL   28  Ahmedabad  93.000000    98.000000

Step 8: Rename a column

In [68]:
# Rename the "Marks" column to "Score"
df.rename(columns={"Marks":"Score"}, inplace=True)
# Display the updated dataset
df

    ID     Name   Age       City      Score
0  101    Rahul  20.0      Surat  85.000000
1  102    Priya  21.0    Navsari  86.142857
2  103  Unknown  22.0      Surat  78.000000
3  104     Amit  20.0    Bharuch  88.000000
4  104     Riya  20.0    Bharuch  88.000000
5  105     Ajay  22.0    Navsari  81.000000
6  106   Naresh  23.0      Surat  90.000000
7  107    jenil  28.0  Ahmedabad  93.000000

Step 9: change data type

In [71]:
# Change the data type of the "Age" column to integer
df["Age"] = df["Age"].astype(int)

# Display the updated dataset
df

    ID     Name  Age       City      Score  Final Score
0  101    RAHUL   20      Surat  85.000000    90.000000
1  102    PRIYA   21    Navsari  86.142857    91.142857
2  103  UNKNOWN   22      Surat  78.000000    83.000000
3  104     AMIT   20    Bharuch  88.000000    93.000000
4  104     RIYA   20    Bharuch  88.000000    93.000000
5  105     AJAY   22    Navsari  81.000000    86.000000
6  106   NARESH   23      Surat  90.000000    95.000000
7  107    JENIL   28  Ahmedabad  93.000000    98.000000

Step 10: Create a New Column

In [70]:
# Create a new column "Final Score"
# Add 5 bonus marks to the "Score" column

df["Final Score"] = df["Score"] + 5

# Display the updated dataset
df

    ID     Name   Age       City      Score  Final Score
0  101    RAHUL  20.0      Surat  85.000000    90.000000
1  102    PRIYA  21.0    Navsari  86.142857    91.142857
2  103  UNKNOWN  22.0      Surat  78.000000    83.000000
3  104     AMIT  20.0    Bharuch  88.000000    93.000000
4  104     RIYA  20.0    Bharuch  88.000000    93.000000
5  105     AJAY  22.0    Navsari  81.000000    86.000000
6  106   NARESH  23.0      Surat  90.000000    95.000000
7  107    JENIL  28.0  Ahmedabad  93.000000    98.000000

Step 11: Convert Text To Uppercase

In [69]:
# Convert all names in the "Name" column to uppercase
df["Name"] = df["Name"].str.upper()

# Display the updated dataset
df

    ID     Name   Age       City      Score
0  101    RAHUL  20.0      Surat  85.000000
1  102    PRIYA  21.0    Navsari  86.142857
2  103  UNKNOWN  22.0      Surat  78.000000
3  104     AMIT  20.0    Bharuch  88.000000
4  104     RIYA  20.0    Bharuch  88.000000
5  105     AJAY  22.0    Navsari  81.000000
6  106   NARESH  23.0      Surat  90.000000
7  107    JENIL  28.0  Ahmedabad  93.000000

Step 12: Convert Text To Lower

In [73]:
# Convert all city names in the "City" column to lowercase
df["City"] = df["City"].str.lower()
# Display the updated dataset
df

    ID     Name  Age       City      Score  Final Score
0  101    RAHUL   20      surat  85.000000    90.000000
1  102    PRIYA   21    navsari  86.142857    91.142857
2  103  UNKNOWN   22      surat  78.000000    83.000000
3  104     AMIT   20    bharuch  88.000000    93.000000
4  104     RIYA   20    bharuch  88.000000    93.000000
5  105     AJAY   22    navsari  81.000000    86.000000
6  106   NARESH   23      surat  90.000000    95.000000
7  107    JENIL   28  ahmedabad  93.000000    98.000000

Step - 13 Remove Extra Spaces

In [74]:
# Remove extra spaces from the "City" column
df["City"] = df["City"].str.strip()

# Display the updated dataset
df

    ID     Name  Age       City      Score  Final Score
0  101    RAHUL   20      surat  85.000000    90.000000
1  102    PRIYA   21    navsari  86.142857    91.142857
2  103  UNKNOWN   22      surat  78.000000    83.000000
3  104     AMIT   20    bharuch  88.000000    93.000000
4  104     RIYA   20    bharuch  88.000000    93.000000
5  105     AJAY   22    navsari  81.000000    86.000000
6  106   NARESH   23      surat  90.000000    95.000000
7  107    JENIL   28  ahmedabad  93.000000    98.000000

Step 14: Sort Dataset

In [75]:
# Sort the dataset by the "Age" column
df.sort_values(by="Age", inplace=True)
# Display the sorted dataset
df

    ID     Name  Age       City      Score  Final Score
0  101    RAHUL   20      surat  85.000000    90.000000
3  104     AMIT   20    bharuch  88.000000    93.000000
4  104     RIYA   20    bharuch  88.000000    93.000000
1  102    PRIYA   21    navsari  86.142857    91.142857
2  103  UNKNOWN   22      surat  78.000000    83.000000
5  105     AJAY   22    navsari  81.000000    86.000000
6  106   NARESH   23      surat  90.000000    95.000000
7  107    JENIL   28  ahmedabad  93.000000    98.000000

Step 15: Save the Cleaned Dataset

In [ ]:
# Save the cleaned dataset
df.to_csv("cleaned_dataset.csv", index=False)

print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!