Enrollment No: 240840116048

## **Practical-3**  Apply fltering, sorting, aggregation, and GroupBy operations on real-world datasets.

**Step1 : Import the pandas Libary**

In [1]:
# Import Pandas library
import pandas as pd

**Step 2: Create a smaple data**

In [2]:
# Create a dictionary containing employee details
data ={
    "Emp_Id":[101,102,103,104,105,106,107,108],
    "Name":["Rahul","Priya","Amit","Riya","Karan","Neha","Vivek","Pooja"],
    "Department":["IT","HR","IT","Finance","HR","Finance","IT","HR"],
    "City":["Surat","Navsari","Surat","Valsad","Surat","Navsari","Valsad","Surat"],
    "Salary":[45000,38000,52000,48000,40000,51000,60000,42000],
    "Experience":[2,1,5,4,2,6,8,3]
}

**Step 3: Create a Dataframe**

In [3]:
# Create a DataFrame from the dictionary
df = pd.DataFrame(data)

# Display the DataFrame
df

   Emp_Id   Name Department     City  Salary  Experience
0     101  Rahul         IT    Surat   45000           2
1     102  Priya         HR  Navsari   38000           1
2     103   Amit         IT    Surat   52000           5
3     104   Riya    Finance   Valsad   48000           4
4     105  Karan         HR    Surat   40000           2
5     106   Neha    Finance  Navsari   51000           6
6     107  Vivek         IT   Valsad   60000           8
7     108  Pooja         HR    Surat   42000           3

**Step 4: Display the Dataset**

In [4]:
# Display the complete DataFrame
df

   Emp_Id   Name Department     City  Salary  Experience
0     101  Rahul         IT    Surat   45000           2
1     102  Priya         HR  Navsari   38000           1
2     103   Amit         IT    Surat   52000           5
3     104   Riya    Finance   Valsad   48000           4
4     105  Karan         HR    Surat   40000           2
5     106   Neha    Finance  Navsari   51000           6
6     107  Vivek         IT   Valsad   60000           8
7     108  Pooja         HR    Surat   42000           3

**Step 5: Filter Data**

In [5]:
# Select only employees working in the IT department.
#The conditon retruns rows where Department is equal to "IT".

df[df['Department']=="IT"]

   Emp_Id   Name Department    City  Salary  Experience
0     101  Rahul         IT   Surat   45000           2
2     103   Amit         IT   Surat   52000           5
6     107  Vivek         IT  Valsad   60000           8

 Task 1: Display Employee with Salary greater than 50000.

In [6]:
# df["Salary"] → selects the Salary column
# df → your DataFrame (employee data)

df[df["Salary"]>50000]

   Emp_Id   Name Department     City  Salary  Experience
2     103   Amit         IT    Surat   52000           5
5     106   Neha    Finance  Navsari   51000           6
6     107  Vivek         IT   Valsad   60000           8

Task 2: Display Employees from surat.

In [7]:
# df → your DataFrame
# Display employees who live in Surat

df[df["City"]=="Surat"]

   Emp_Id   Name Department   City  Salary  Experience
0     101  Rahul         IT  Surat   45000           2
2     103   Amit         IT  Surat   52000           5
4     105  Karan         HR  Surat   40000           2
7     108  Pooja         HR  Surat   42000           3

Task 3: Apply Mutliple conditions

In [8]:
# Display employees who are from the IT department
# AND whose salary is greater than 50,000

df[(df["Department"]=="IT")&(df["Salary"]>50000)]

# Both conditions must be True:
# 1. Department must be "IT"
# 2. Salary must be greater than 50,000

   Emp_Id   Name Department    City  Salary  Experience
2     103   Amit         IT   Surat   52000           5
6     107  Vivek         IT  Valsad   60000           8

**Step 6: Sort data**

Task 1: Sort Salary in Ascending Order.

In [9]:
# Sort the employee data by Salary
# By default, the salary is sorted in ascending order
# (lowest salary to highest salary)

df.sort_values(by="Salary")

   Emp_Id   Name Department     City  Salary  Experience
1     102  Priya         HR  Navsari   38000           1
4     105  Karan         HR    Surat   40000           2
7     108  Pooja         HR    Surat   42000           3
0     101  Rahul         IT    Surat   45000           2
3     104   Riya    Finance   Valsad   48000           4
5     106   Neha    Finance  Navsari   51000           6
2     103   Amit         IT    Surat   52000           5
6     107  Vivek         IT   Valsad   60000           8

Task 2: Sort Salary in descending Order.

In [10]:
# Sort the employee data based on the Salary column
# ascending=False means sort from highest salary to lowest salary
# So, the employee with the highest salary will appear first

df.sort_values(by="Salary",ascending=False)

   Emp_Id   Name Department     City  Salary  Experience
6     107  Vivek         IT   Valsad   60000           8
2     103   Amit         IT    Surat   52000           5
5     106   Neha    Finance  Navsari   51000           6
3     104   Riya    Finance   Valsad   48000           4
0     101  Rahul         IT    Surat   45000           2
7     108  Pooja         HR    Surat   42000           3
4     105  Karan         HR    Surat   40000           2
1     102  Priya         HR  Navsari   38000           1

Task 3: Sort by Department and Salary.

In [11]:
# Sort the employee data using two columns:
# 1. Department → sort in ascending order (A to Z)
# 2. Salary → sort in descending order (highest to lowest)

df.sort_values(by=["Department","Salary"], ascending=[True,False])

   Emp_Id   Name Department     City  Salary  Experience
5     106   Neha    Finance  Navsari   51000           6
3     104   Riya    Finance   Valsad   48000           4
7     108  Pooja         HR    Surat   42000           3
4     105  Karan         HR    Surat   40000           2
1     102  Priya         HR  Navsari   38000           1
6     107  Vivek         IT   Valsad   60000           8
2     103   Amit         IT    Surat   52000           5
0     101  Rahul         IT    Surat   45000           2

**Step 7: Perform Aggregation**

Task 1: Calculate Total Salary.

In [12]:
# Calculate the total salary of all employees
# df["Salary"] → selects the Salary column
# .sum() → adds all the salary values together

df["Salary"].sum()

np.int64(376000)

Task 2: Calculate Average Salary.

In [13]:
# Calculate the average salary of all employees
# .mean() → calculates the average (mean) of the salary values

df["Salary"].mean()

np.float64(47000.0)

Task 3: Find Highest Salary.

In [14]:
# Find the highest salary among all employees
# .max() → finds the largest value in the Salary column

df["Salary"].max()

60000

Task 4: Find the lowest Salary.

In [15]:
# Find the lowest salary among all employees
# .min() → finds the smallest value in the Salary column

df["Salary"].min()

38000

Task 5: Count Employees

In [16]:
# Count the total number of employee IDs
# .count() → counts the number of non-empty values in the column

df["Emp_Id"].count()

np.int64(8)

**Step 8: Perform GroupB operations**

Task 1: Average Salary Department-wise

In [17]:
# Group employees according to their Department
# df.groupby("Department") → creates separate groups for each department
# ["Salary"] → selects the Salary column from each department
# .mean() → calculates the average salary for each department

df.groupby("Department")["Salary"].mean()

Department
Finance    49500.000000
HR         40000.000000
IT         52333.333333
Name: Salary, dtype: float64

Task 2: Minimum Salary Department-wise

In [18]:
# Group employees by Department
# ["Salary"] → selects the Salary column for each department
# .min() → finds the lowest salary in each department

df.groupby("Department")["Salary"].min()

Department
Finance    48000
HR         38000
IT         45000
Name: Salary, dtype: int64

Task 3: Count Employees by Department-wise

In [19]:
# Group employees by Department
# ["Emp_Id"] → selects the Employee ID column
# .count() → counts the number of Employee IDs in each department

df.groupby("Department")["Emp_Id"].count()

Department
Finance    2
HR         3
IT         3
Name: Emp_Id, dtype: int64

Task 4: Total Salary Department-wise

In [20]:
# Group employees according to their Department
# ["Salary"] → selects the Salary column
# .sum() → adds all salaries within each department

df.groupby("Department")["Salary"].sum()

Department
Finance     99000
HR         120000
IT         157000
Name: Salary, dtype: int64

Task 5: Maximum Salary Department-wise

In [21]:
# Group employees according to their Department
# ["Salary"] → selects the Salary column for each department
# .max() → finds the highest salary in each department

df.groupby("Department")["Salary"].max()

Department
Finance    51000
HR         42000
IT         60000
Name: Salary, dtype: int64

Task 6: Group By City Average Salary

In [22]:
# Group employees according to their City
# ["Salary"] → selects the Salary column for each city
# .mean() → calculates the average salary for each city

df.groupby("City")["Salary"].mean()

City
Navsari    44500.0
Surat      44750.0
Valsad     54000.0
Name: Salary, dtype: float64

 **Step 9: Multiple Aggregation Functions**

In [23]:
# Group employees by Department
# ["Salary"] → selects the Salary column for each department
# .agg() → applies multiple functions to the Salary column

df.groupby("Department")["Salary"].agg(["count","sum","mean","min","max"])

# count → counts the number of salary values (employees)
# sum   → calculates the total salary
# mean  → calculates the average salary
# min   → finds the lowest salary
# max   → finds the highest salary

            count     sum          mean    min    max
Department
Finance         2   99000  49500.000000  48000  51000
HR              3  120000  40000.000000  38000  42000
IT              3  157000  52333.333333  45000  60000

**Step 10: Save Result**

In [24]:
# Save the DataFrame as a CSV file
# "Employee_Data.csv" → name of the CSV file to be created
# index=False → does not save the DataFrame index as an extra column

df.to_csv("Employee_Data.csv",index=False)
print("Dataset create successfully.")

Dataset create successfully.

Download CSV file

In [25]:
# Save the DataFrame as a CSV file

df.to_csv("Employee_Data.csv",index=False)

# Import the 'files' module from Google Colab
# This module is used to download files to your computer

from google.colab import files

# Download the CSV file to your computer
files.download("Employee_Data.csv")